//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PhongKhamEntities : DbContext
    {
        public PhongKhamEntities()
            : base("name=PhongKhamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int SP_Account_DELETE(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Account_DELETE", usernameParameter);
        }
    
        public virtual ObjectResult<SP_Account_GetAll_Result> SP_Account_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Account_GetAll_Result>("SP_Account_GetAll");
        }
    
        public virtual ObjectResult<SP_Account_GetByUsername_Result> SP_Account_GetByUsername(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Account_GetByUsername_Result>("SP_Account_GetByUsername", usernameParameter);
        }
    
        public virtual int SP_Account_INSERT(string username, string password, string email, Nullable<bool> sex, string name, Nullable<System.DateTime> birthday, string adress, string phone, Nullable<System.Guid> iD_Position, string avatar)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(bool));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            var adressParameter = adress != null ?
                new ObjectParameter("Adress", adress) :
                new ObjectParameter("Adress", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var iD_PositionParameter = iD_Position.HasValue ?
                new ObjectParameter("ID_Position", iD_Position) :
                new ObjectParameter("ID_Position", typeof(System.Guid));
    
            var avatarParameter = avatar != null ?
                new ObjectParameter("Avatar", avatar) :
                new ObjectParameter("Avatar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Account_INSERT", usernameParameter, passwordParameter, emailParameter, sexParameter, nameParameter, birthdayParameter, adressParameter, phoneParameter, iD_PositionParameter, avatarParameter);
        }
    
        public virtual int SP_Account_UPDATE(string username, string password, string email, Nullable<bool> sex, string name, Nullable<System.DateTime> birthday, string adress, string phone, Nullable<System.Guid> iD_Position, string avatar)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var sexParameter = sex.HasValue ?
                new ObjectParameter("Sex", sex) :
                new ObjectParameter("Sex", typeof(bool));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var birthdayParameter = birthday.HasValue ?
                new ObjectParameter("Birthday", birthday) :
                new ObjectParameter("Birthday", typeof(System.DateTime));
    
            var adressParameter = adress != null ?
                new ObjectParameter("Adress", adress) :
                new ObjectParameter("Adress", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var iD_PositionParameter = iD_Position.HasValue ?
                new ObjectParameter("ID_Position", iD_Position) :
                new ObjectParameter("ID_Position", typeof(System.Guid));
    
            var avatarParameter = avatar != null ?
                new ObjectParameter("Avatar", avatar) :
                new ObjectParameter("Avatar", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Account_UPDATE", usernameParameter, passwordParameter, emailParameter, sexParameter, nameParameter, birthdayParameter, adressParameter, phoneParameter, iD_PositionParameter, avatarParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_BacSi_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BacSi_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_BacSi_GetAll_Result> SP_BacSi_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BacSi_GetAll_Result>("SP_BacSi_GetAll");
        }
    
        public virtual ObjectResult<SP_BacSi_GetByID_Result> SP_BacSi_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BacSi_GetByID_Result>("SP_BacSi_GetByID", iDParameter);
        }
    
        public virtual int SP_BacSi_INSERT(Nullable<System.Guid> iD, string name, Nullable<System.Guid> iD_PhongBan, string linkImage)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var iD_PhongBanParameter = iD_PhongBan.HasValue ?
                new ObjectParameter("ID_PhongBan", iD_PhongBan) :
                new ObjectParameter("ID_PhongBan", typeof(System.Guid));
    
            var linkImageParameter = linkImage != null ?
                new ObjectParameter("LinkImage", linkImage) :
                new ObjectParameter("LinkImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BacSi_INSERT", iDParameter, nameParameter, iD_PhongBanParameter, linkImageParameter);
        }
    
        public virtual int SP_BacSi_UPDATE(Nullable<System.Guid> iD, string name, Nullable<System.Guid> iD_PhongBan, string linkImage)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var iD_PhongBanParameter = iD_PhongBan.HasValue ?
                new ObjectParameter("ID_PhongBan", iD_PhongBan) :
                new ObjectParameter("ID_PhongBan", typeof(System.Guid));
    
            var linkImageParameter = linkImage != null ?
                new ObjectParameter("LinkImage", linkImage) :
                new ObjectParameter("LinkImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_BacSi_UPDATE", iDParameter, nameParameter, iD_PhongBanParameter, linkImageParameter);
        }
    
        public virtual int SP_CoSoVatChat_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CoSoVatChat_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_CoSoVatChat_GetAll_Result> SP_CoSoVatChat_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CoSoVatChat_GetAll_Result>("SP_CoSoVatChat_GetAll");
        }
    
        public virtual ObjectResult<SP_CoSoVatChat_GetByID_Result> SP_CoSoVatChat_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CoSoVatChat_GetByID_Result>("SP_CoSoVatChat_GetByID", iDParameter);
        }
    
        public virtual int SP_CoSoVatChat_INSERT(Nullable<System.Guid> iD, string gioiThieu, string linkImage, Nullable<int> index, string hrefAjax)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var gioiThieuParameter = gioiThieu != null ?
                new ObjectParameter("GioiThieu", gioiThieu) :
                new ObjectParameter("GioiThieu", typeof(string));
    
            var linkImageParameter = linkImage != null ?
                new ObjectParameter("LinkImage", linkImage) :
                new ObjectParameter("LinkImage", typeof(string));
    
            var indexParameter = index.HasValue ?
                new ObjectParameter("Index", index) :
                new ObjectParameter("Index", typeof(int));
    
            var hrefAjaxParameter = hrefAjax != null ?
                new ObjectParameter("hrefAjax", hrefAjax) :
                new ObjectParameter("hrefAjax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CoSoVatChat_INSERT", iDParameter, gioiThieuParameter, linkImageParameter, indexParameter, hrefAjaxParameter);
        }
    
        public virtual int SP_CoSoVatChat_UPDATE(Nullable<System.Guid> iD, string gioiThieu, string linkImage, Nullable<int> index, string hrefAjax)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var gioiThieuParameter = gioiThieu != null ?
                new ObjectParameter("GioiThieu", gioiThieu) :
                new ObjectParameter("GioiThieu", typeof(string));
    
            var linkImageParameter = linkImage != null ?
                new ObjectParameter("LinkImage", linkImage) :
                new ObjectParameter("LinkImage", typeof(string));
    
            var indexParameter = index.HasValue ?
                new ObjectParameter("Index", index) :
                new ObjectParameter("Index", typeof(int));
    
            var hrefAjaxParameter = hrefAjax != null ?
                new ObjectParameter("hrefAjax", hrefAjax) :
                new ObjectParameter("hrefAjax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CoSoVatChat_UPDATE", iDParameter, gioiThieuParameter, linkImageParameter, indexParameter, hrefAjaxParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_CTCoSoVatChat_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CTCoSoVatChat_DELETE", iDParameter);
        }
    
        public virtual int SP_CTCoSoVatChat_DELETEForID(Nullable<System.Guid> iD_CoSoVatChat)
        {
            var iD_CoSoVatChatParameter = iD_CoSoVatChat.HasValue ?
                new ObjectParameter("ID_CoSoVatChat", iD_CoSoVatChat) :
                new ObjectParameter("ID_CoSoVatChat", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CTCoSoVatChat_DELETEForID", iD_CoSoVatChatParameter);
        }
    
        public virtual ObjectResult<SP_CTCoSoVatChat_GetAll_Result> SP_CTCoSoVatChat_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CTCoSoVatChat_GetAll_Result>("SP_CTCoSoVatChat_GetAll");
        }
    
        public virtual ObjectResult<SP_CTCoSoVatChat_GetByID_Result> SP_CTCoSoVatChat_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CTCoSoVatChat_GetByID_Result>("SP_CTCoSoVatChat_GetByID", iDParameter);
        }
    
        public virtual ObjectResult<SP_CTCoSoVatChat_GetGroupByID_Result> SP_CTCoSoVatChat_GetGroupByID(Nullable<System.Guid> iD_CoSoVatChat)
        {
            var iD_CoSoVatChatParameter = iD_CoSoVatChat.HasValue ?
                new ObjectParameter("ID_CoSoVatChat", iD_CoSoVatChat) :
                new ObjectParameter("ID_CoSoVatChat", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CTCoSoVatChat_GetGroupByID_Result>("SP_CTCoSoVatChat_GetGroupByID", iD_CoSoVatChatParameter);
        }
    
        public virtual int SP_CTCoSoVatChat_INSERT(Nullable<System.Guid> iD, Nullable<System.Guid> iD_CoSoVatChat, string linkImage, string noiDung)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var iD_CoSoVatChatParameter = iD_CoSoVatChat.HasValue ?
                new ObjectParameter("ID_CoSoVatChat", iD_CoSoVatChat) :
                new ObjectParameter("ID_CoSoVatChat", typeof(System.Guid));
    
            var linkImageParameter = linkImage != null ?
                new ObjectParameter("LinkImage", linkImage) :
                new ObjectParameter("LinkImage", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CTCoSoVatChat_INSERT", iDParameter, iD_CoSoVatChatParameter, linkImageParameter, noiDungParameter);
        }
    
        public virtual int SP_CTCoSoVatChat_UPDATE(Nullable<System.Guid> iD, Nullable<System.Guid> iD_CoSoVatChat, string linkImage, string noiDung)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var iD_CoSoVatChatParameter = iD_CoSoVatChat.HasValue ?
                new ObjectParameter("ID_CoSoVatChat", iD_CoSoVatChat) :
                new ObjectParameter("ID_CoSoVatChat", typeof(System.Guid));
    
            var linkImageParameter = linkImage != null ?
                new ObjectParameter("LinkImage", linkImage) :
                new ObjectParameter("LinkImage", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CTCoSoVatChat_UPDATE", iDParameter, iD_CoSoVatChatParameter, linkImageParameter, noiDungParameter);
        }
    
        public virtual int SP_DiaChi_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DiaChi_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_DiaChi_GetAll_Result> SP_DiaChi_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DiaChi_GetAll_Result>("SP_DiaChi_GetAll");
        }
    
        public virtual ObjectResult<SP_DiaChi_GetByID_Result> SP_DiaChi_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DiaChi_GetByID_Result>("SP_DiaChi_GetByID", iDParameter);
        }
    
        public virtual int SP_DiaChi_INSERT(Nullable<System.Guid> iD, string mobile, string adress, string hotline)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var adressParameter = adress != null ?
                new ObjectParameter("Adress", adress) :
                new ObjectParameter("Adress", typeof(string));
    
            var hotlineParameter = hotline != null ?
                new ObjectParameter("Hotline", hotline) :
                new ObjectParameter("Hotline", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DiaChi_INSERT", iDParameter, mobileParameter, adressParameter, hotlineParameter);
        }
    
        public virtual int SP_DiaChi_UPDATE(Nullable<System.Guid> iD, string mobile, string adress, string hotline)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var adressParameter = adress != null ?
                new ObjectParameter("Adress", adress) :
                new ObjectParameter("Adress", typeof(string));
    
            var hotlineParameter = hotline != null ?
                new ObjectParameter("Hotline", hotline) :
                new ObjectParameter("Hotline", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DiaChi_UPDATE", iDParameter, mobileParameter, adressParameter, hotlineParameter);
        }
    
        public virtual int SP_DichVu_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DichVu_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_DichVu_GetAll_Result> SP_DichVu_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DichVu_GetAll_Result>("SP_DichVu_GetAll");
        }
    
        public virtual ObjectResult<SP_DichVu_GetByID_Result> SP_DichVu_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_DichVu_GetByID_Result>("SP_DichVu_GetByID", iDParameter);
        }
    
        public virtual int SP_DichVu_INSERT(Nullable<System.Guid> iD, string icon, string name, string gioiThieu, string hrefAjax)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var iconParameter = icon != null ?
                new ObjectParameter("Icon", icon) :
                new ObjectParameter("Icon", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var gioiThieuParameter = gioiThieu != null ?
                new ObjectParameter("GioiThieu", gioiThieu) :
                new ObjectParameter("GioiThieu", typeof(string));
    
            var hrefAjaxParameter = hrefAjax != null ?
                new ObjectParameter("hrefAjax", hrefAjax) :
                new ObjectParameter("hrefAjax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DichVu_INSERT", iDParameter, iconParameter, nameParameter, gioiThieuParameter, hrefAjaxParameter);
        }
    
        public virtual int SP_DichVu_UPDATE(Nullable<System.Guid> iD, string icon, string name, string gioiThieu, string hrefAjax)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var iconParameter = icon != null ?
                new ObjectParameter("Icon", icon) :
                new ObjectParameter("Icon", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var gioiThieuParameter = gioiThieu != null ?
                new ObjectParameter("GioiThieu", gioiThieu) :
                new ObjectParameter("GioiThieu", typeof(string));
    
            var hrefAjaxParameter = hrefAjax != null ?
                new ObjectParameter("hrefAjax", hrefAjax) :
                new ObjectParameter("hrefAjax", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DichVu_UPDATE", iDParameter, iconParameter, nameParameter, gioiThieuParameter, hrefAjaxParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_GopY_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GopY_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_GopY_GetAll_Result> SP_GopY_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GopY_GetAll_Result>("SP_GopY_GetAll");
        }
    
        public virtual ObjectResult<SP_GopY_GetByID_Result> SP_GopY_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GopY_GetByID_Result>("SP_GopY_GetByID", iDParameter);
        }
    
        public virtual int SP_GopY_INSERT(Nullable<System.Guid> iD, Nullable<System.DateTime> thoiGian, string hoTen, string dienThoai, string email, string noiDung)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GopY_INSERT", iDParameter, thoiGianParameter, hoTenParameter, dienThoaiParameter, emailParameter, noiDungParameter);
        }
    
        public virtual int SP_GopY_UPDATE(Nullable<System.Guid> iD, Nullable<System.DateTime> thoiGian, string hoTen, string dienThoai, string email, string noiDung)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var thoiGianParameter = thoiGian.HasValue ?
                new ObjectParameter("ThoiGian", thoiGian) :
                new ObjectParameter("ThoiGian", typeof(System.DateTime));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var dienThoaiParameter = dienThoai != null ?
                new ObjectParameter("DienThoai", dienThoai) :
                new ObjectParameter("DienThoai", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GopY_UPDATE", iDParameter, thoiGianParameter, hoTenParameter, dienThoaiParameter, emailParameter, noiDungParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_Menu_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Menu_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Menu_GetAll_Result> SP_Menu_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Menu_GetAll_Result>("SP_Menu_GetAll");
        }
    
        public virtual ObjectResult<SP_Menu_GetByID_Result> SP_Menu_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Menu_GetByID_Result>("SP_Menu_GetByID", iDParameter);
        }
    
        public virtual int SP_Menu_INSERT(Nullable<System.Guid> iD, string display, Nullable<int> rank, string neo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var displayParameter = display != null ?
                new ObjectParameter("Display", display) :
                new ObjectParameter("Display", typeof(string));
    
            var rankParameter = rank.HasValue ?
                new ObjectParameter("Rank", rank) :
                new ObjectParameter("Rank", typeof(int));
    
            var neoParameter = neo != null ?
                new ObjectParameter("Neo", neo) :
                new ObjectParameter("Neo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Menu_INSERT", iDParameter, displayParameter, rankParameter, neoParameter);
        }
    
        public virtual int SP_Menu_UPDATE(Nullable<System.Guid> iD, string display, Nullable<int> rank, string neo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var displayParameter = display != null ?
                new ObjectParameter("Display", display) :
                new ObjectParameter("Display", typeof(string));
    
            var rankParameter = rank.HasValue ?
                new ObjectParameter("Rank", rank) :
                new ObjectParameter("Rank", typeof(int));
    
            var neoParameter = neo != null ?
                new ObjectParameter("Neo", neo) :
                new ObjectParameter("Neo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Menu_UPDATE", iDParameter, displayParameter, rankParameter, neoParameter);
        }
    
        public virtual int SP_PhongBan_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PhongBan_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_PhongBan_GetAll_Result> SP_PhongBan_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PhongBan_GetAll_Result>("SP_PhongBan_GetAll");
        }
    
        public virtual ObjectResult<SP_PhongBan_GetByID_Result> SP_PhongBan_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PhongBan_GetByID_Result>("SP_PhongBan_GetByID", iDParameter);
        }
    
        public virtual int SP_PhongBan_INSERT(Nullable<System.Guid> iD, string name, string moTa)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PhongBan_INSERT", iDParameter, nameParameter, moTaParameter);
        }
    
        public virtual int SP_PhongBan_UPDATE(Nullable<System.Guid> iD, string name, string moTa)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PhongBan_UPDATE", iDParameter, nameParameter, moTaParameter);
        }
    
        public virtual int SP_Position_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Position_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Position_GetAll_Result> SP_Position_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Position_GetAll_Result>("SP_Position_GetAll");
        }
    
        public virtual ObjectResult<SP_Position_GetByID_Result> SP_Position_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Position_GetByID_Result>("SP_Position_GetByID", iDParameter);
        }
    
        public virtual int SP_Position_INSERT(Nullable<System.Guid> iD, string name, string mieuTa)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var mieuTaParameter = mieuTa != null ?
                new ObjectParameter("MieuTa", mieuTa) :
                new ObjectParameter("MieuTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Position_INSERT", iDParameter, nameParameter, mieuTaParameter);
        }
    
        public virtual int SP_Position_UPDATE(Nullable<System.Guid> iD, string name, string mieuTa)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var mieuTaParameter = mieuTa != null ?
                new ObjectParameter("MieuTa", mieuTa) :
                new ObjectParameter("MieuTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Position_UPDATE", iDParameter, nameParameter, mieuTaParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int SP_SanPham_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SanPham_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_SanPham_GetAll_Result> SP_SanPham_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SanPham_GetAll_Result>("SP_SanPham_GetAll");
        }
    
        public virtual ObjectResult<SP_SanPham_GetByID_Result> SP_SanPham_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SanPham_GetByID_Result>("SP_SanPham_GetByID", iDParameter);
        }
    
        public virtual int SP_SanPham_INSERT(Nullable<System.Guid> iD, string linkImage, string name, Nullable<int> giaTien, Nullable<int> rank, string thongTin)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var linkImageParameter = linkImage != null ?
                new ObjectParameter("LinkImage", linkImage) :
                new ObjectParameter("LinkImage", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(int));
    
            var rankParameter = rank.HasValue ?
                new ObjectParameter("Rank", rank) :
                new ObjectParameter("Rank", typeof(int));
    
            var thongTinParameter = thongTin != null ?
                new ObjectParameter("ThongTin", thongTin) :
                new ObjectParameter("ThongTin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SanPham_INSERT", iDParameter, linkImageParameter, nameParameter, giaTienParameter, rankParameter, thongTinParameter);
        }
    
        public virtual int SP_SanPham_UPDATE(Nullable<System.Guid> iD, string linkImage, string name, Nullable<int> giaTien, Nullable<int> rank, string thongTin)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var linkImageParameter = linkImage != null ?
                new ObjectParameter("LinkImage", linkImage) :
                new ObjectParameter("LinkImage", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var giaTienParameter = giaTien.HasValue ?
                new ObjectParameter("GiaTien", giaTien) :
                new ObjectParameter("GiaTien", typeof(int));
    
            var rankParameter = rank.HasValue ?
                new ObjectParameter("Rank", rank) :
                new ObjectParameter("Rank", typeof(int));
    
            var thongTinParameter = thongTin != null ?
                new ObjectParameter("ThongTin", thongTin) :
                new ObjectParameter("ThongTin", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SanPham_UPDATE", iDParameter, linkImageParameter, nameParameter, giaTienParameter, rankParameter, thongTinParameter);
        }
    
        public virtual int SP_Slogan_DELETE(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Slogan_DELETE", iDParameter);
        }
    
        public virtual ObjectResult<SP_Slogan_GetAll_Result> SP_Slogan_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Slogan_GetAll_Result>("SP_Slogan_GetAll");
        }
    
        public virtual ObjectResult<SP_Slogan_GetByID_Result> SP_Slogan_GetByID(Nullable<System.Guid> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Slogan_GetByID_Result>("SP_Slogan_GetByID", iDParameter);
        }
    
        public virtual int SP_Slogan_INSERT(Nullable<System.Guid> iD, string dichVu, string slogan_DichVu, string veChungToi, string slogan_VeChungToi, string nameContent_VeChungToi, string content_VeChungToi, string cSVC, string slogan_CSVC, string bacSi, string slogan_BacSi, string lienHe, string slogan_Lienhe, string gioiThieu, string imageGioiThieu, string imagePage, string sloganPage, string logoPage)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var dichVuParameter = dichVu != null ?
                new ObjectParameter("DichVu", dichVu) :
                new ObjectParameter("DichVu", typeof(string));
    
            var slogan_DichVuParameter = slogan_DichVu != null ?
                new ObjectParameter("Slogan_DichVu", slogan_DichVu) :
                new ObjectParameter("Slogan_DichVu", typeof(string));
    
            var veChungToiParameter = veChungToi != null ?
                new ObjectParameter("VeChungToi", veChungToi) :
                new ObjectParameter("VeChungToi", typeof(string));
    
            var slogan_VeChungToiParameter = slogan_VeChungToi != null ?
                new ObjectParameter("Slogan_VeChungToi", slogan_VeChungToi) :
                new ObjectParameter("Slogan_VeChungToi", typeof(string));
    
            var nameContent_VeChungToiParameter = nameContent_VeChungToi != null ?
                new ObjectParameter("nameContent_VeChungToi", nameContent_VeChungToi) :
                new ObjectParameter("nameContent_VeChungToi", typeof(string));
    
            var content_VeChungToiParameter = content_VeChungToi != null ?
                new ObjectParameter("Content_VeChungToi", content_VeChungToi) :
                new ObjectParameter("Content_VeChungToi", typeof(string));
    
            var cSVCParameter = cSVC != null ?
                new ObjectParameter("CSVC", cSVC) :
                new ObjectParameter("CSVC", typeof(string));
    
            var slogan_CSVCParameter = slogan_CSVC != null ?
                new ObjectParameter("Slogan_CSVC", slogan_CSVC) :
                new ObjectParameter("Slogan_CSVC", typeof(string));
    
            var bacSiParameter = bacSi != null ?
                new ObjectParameter("BacSi", bacSi) :
                new ObjectParameter("BacSi", typeof(string));
    
            var slogan_BacSiParameter = slogan_BacSi != null ?
                new ObjectParameter("Slogan_BacSi", slogan_BacSi) :
                new ObjectParameter("Slogan_BacSi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var slogan_LienheParameter = slogan_Lienhe != null ?
                new ObjectParameter("Slogan_Lienhe", slogan_Lienhe) :
                new ObjectParameter("Slogan_Lienhe", typeof(string));
    
            var gioiThieuParameter = gioiThieu != null ?
                new ObjectParameter("GioiThieu", gioiThieu) :
                new ObjectParameter("GioiThieu", typeof(string));
    
            var imageGioiThieuParameter = imageGioiThieu != null ?
                new ObjectParameter("ImageGioiThieu", imageGioiThieu) :
                new ObjectParameter("ImageGioiThieu", typeof(string));
    
            var imagePageParameter = imagePage != null ?
                new ObjectParameter("ImagePage", imagePage) :
                new ObjectParameter("ImagePage", typeof(string));
    
            var sloganPageParameter = sloganPage != null ?
                new ObjectParameter("SloganPage", sloganPage) :
                new ObjectParameter("SloganPage", typeof(string));
    
            var logoPageParameter = logoPage != null ?
                new ObjectParameter("LogoPage", logoPage) :
                new ObjectParameter("LogoPage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Slogan_INSERT", iDParameter, dichVuParameter, slogan_DichVuParameter, veChungToiParameter, slogan_VeChungToiParameter, nameContent_VeChungToiParameter, content_VeChungToiParameter, cSVCParameter, slogan_CSVCParameter, bacSiParameter, slogan_BacSiParameter, lienHeParameter, slogan_LienheParameter, gioiThieuParameter, imageGioiThieuParameter, imagePageParameter, sloganPageParameter, logoPageParameter);
        }
    
        public virtual int SP_Slogan_UPDATE(Nullable<System.Guid> iD, string dichVu, string slogan_DichVu, string veChungToi, string slogan_VeChungToi, string nameContent_VeChungToi, string content_VeChungToi, string cSVC, string slogan_CSVC, string bacSi, string slogan_BacSi, string lienHe, string slogan_Lienhe, string gioiThieu, string imageGioiThieu, string imagePage, string sloganPage, string logoPage)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(System.Guid));
    
            var dichVuParameter = dichVu != null ?
                new ObjectParameter("DichVu", dichVu) :
                new ObjectParameter("DichVu", typeof(string));
    
            var slogan_DichVuParameter = slogan_DichVu != null ?
                new ObjectParameter("Slogan_DichVu", slogan_DichVu) :
                new ObjectParameter("Slogan_DichVu", typeof(string));
    
            var veChungToiParameter = veChungToi != null ?
                new ObjectParameter("VeChungToi", veChungToi) :
                new ObjectParameter("VeChungToi", typeof(string));
    
            var slogan_VeChungToiParameter = slogan_VeChungToi != null ?
                new ObjectParameter("Slogan_VeChungToi", slogan_VeChungToi) :
                new ObjectParameter("Slogan_VeChungToi", typeof(string));
    
            var nameContent_VeChungToiParameter = nameContent_VeChungToi != null ?
                new ObjectParameter("nameContent_VeChungToi", nameContent_VeChungToi) :
                new ObjectParameter("nameContent_VeChungToi", typeof(string));
    
            var content_VeChungToiParameter = content_VeChungToi != null ?
                new ObjectParameter("Content_VeChungToi", content_VeChungToi) :
                new ObjectParameter("Content_VeChungToi", typeof(string));
    
            var cSVCParameter = cSVC != null ?
                new ObjectParameter("CSVC", cSVC) :
                new ObjectParameter("CSVC", typeof(string));
    
            var slogan_CSVCParameter = slogan_CSVC != null ?
                new ObjectParameter("Slogan_CSVC", slogan_CSVC) :
                new ObjectParameter("Slogan_CSVC", typeof(string));
    
            var bacSiParameter = bacSi != null ?
                new ObjectParameter("BacSi", bacSi) :
                new ObjectParameter("BacSi", typeof(string));
    
            var slogan_BacSiParameter = slogan_BacSi != null ?
                new ObjectParameter("Slogan_BacSi", slogan_BacSi) :
                new ObjectParameter("Slogan_BacSi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var slogan_LienheParameter = slogan_Lienhe != null ?
                new ObjectParameter("Slogan_Lienhe", slogan_Lienhe) :
                new ObjectParameter("Slogan_Lienhe", typeof(string));
    
            var gioiThieuParameter = gioiThieu != null ?
                new ObjectParameter("GioiThieu", gioiThieu) :
                new ObjectParameter("GioiThieu", typeof(string));
    
            var imageGioiThieuParameter = imageGioiThieu != null ?
                new ObjectParameter("ImageGioiThieu", imageGioiThieu) :
                new ObjectParameter("ImageGioiThieu", typeof(string));
    
            var imagePageParameter = imagePage != null ?
                new ObjectParameter("ImagePage", imagePage) :
                new ObjectParameter("ImagePage", typeof(string));
    
            var sloganPageParameter = sloganPage != null ?
                new ObjectParameter("SloganPage", sloganPage) :
                new ObjectParameter("SloganPage", typeof(string));
    
            var logoPageParameter = logoPage != null ?
                new ObjectParameter("LogoPage", logoPage) :
                new ObjectParameter("LogoPage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Slogan_UPDATE", iDParameter, dichVuParameter, slogan_DichVuParameter, veChungToiParameter, slogan_VeChungToiParameter, nameContent_VeChungToiParameter, content_VeChungToiParameter, cSVCParameter, slogan_CSVCParameter, bacSiParameter, slogan_BacSiParameter, lienHeParameter, slogan_LienheParameter, gioiThieuParameter, imageGioiThieuParameter, imagePageParameter, sloganPageParameter, logoPageParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
